#!/bin/bash

f() {
    for cur_dir in "$@"
    do
        if [[ -d "$cur_dir" ]] 
        then
            f "$cur_dir"/*
        elif [[ ! -e "$cur_dir" &&  -L "$cur_dir" ]]
        then
            echo "$cur_dir"
        fi 
    done
}

f "$@"
