#!/bin/bash

f() {
    for cur_dir in "$@"
    do
        if [[ -d "$cur_dir" ]] 
        then
            f "$cur_dir"/*
        elif [[ -f "$cur_dir" ]]
        then
              echo "$cur_dir"
           if [[ ! -e "$cur_dir" && ! -f "$cur_dir" ]]
           then
              echo "$cur_dir"
          fi 
        fi
    done
}

f "$@"
