#!/bin/bash

for cur_name in "$@"
do
    if [[ -f $cur_name ]]; then
        read -e -p "Edit name: " -i "$cur_name" new_name
    fi
    if [ "$new_name" ]; then
        mv "$cur_name" "$new_name"
    fi
done
