#!/bin/bash
update_time="$1"
shift
process="$@"
current=`$process`
while true
do
   sleep "$update_time"
   echo "$current"
   after_sleep=`$process`
   DIFF="$(diff -u <(echo "$current") <(echo "$after_sleep"))"
   echo "$DIFF" 
   current="$after_sleep"
   done
